name: CI - Tests & Quality

on:
  pull_request:
    branches: [ main, develop, release/* ]
  push:
    branches: [ main, develop, release/* ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run comprehensive unit tests
      run: |
        python scripts/run_tests.py
        
    - name: Test import structure
      run: |
        python -c "import sys; sys.path.append('src'); import main; print('✅ Main module imports successfully')"
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          logs/
          test-results.xml
        retention-days: 30

    - name: Comment test results on PR  
      uses: actions/github-script@v6
      if: always() && github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          
          let testStatus = '✅ All tests passed';
          let testDetails = 'Unit tests completed successfully!';
          
          const body = `## Test Results 🧪
          
${testStatus}

<details>
<summary>Test Details</summary>

\`\`\`
${testDetails}
\`\`\`

</details>

---
*Automated by GitHub Actions CI/CD Pipeline*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
