name: Release Branch - Tests and Build

on:
  push:
    branches: [ 'release/**' ]
  pull_request:
    branches: [ 'release/**' ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        python scripts/run_tests.py
        
    - name: Build application (release branch)
      if: github.event_name == 'push'
      run: |
        # Install build tools
        pip install pyinstaller
        
        # Download and install Inno Setup
        $innoUrl = "https://files.jrsoftware.org/is/6/innosetup-6.4.3.exe"
        Invoke-WebRequest -Uri $innoUrl -OutFile "innosetup.exe"
        Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -Wait
        
        # Build the application
        ./build_all.bat
        
    - name: Upload release artifacts
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: release-build-${{ github.sha }}
        path: |
          releases/
          dist/
        retention-days: 30
