name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run basic tests
      run: |
        # Run any existing test files
        if (Test-Path "tests/") {
          pytest tests/ --cov=src --cov-report=xml --cov-report=html
        }
        if (Test-Path "test_*.py") {
          python test_gui_components.py
        }
    
    - name: Test import structure
      run: |
        python -c "import sys; sys.path.append('src'); import main; print('✅ Main module imports successfully')"
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  build-test:
    runs-on: windows-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Install Inno Setup
      run: |
        choco install innosetup
    
    - name: Test build process
      run: |
        # Test executable build
        cd build
        ./build_executable.bat
        
        # Verify executable exists
        if (!(Test-Path "../dist/PortalReceiptsApp/PortalReceiptsApp.exe")) {
          throw "Executable not created"
        }
        
        echo "✅ Executable build successful"
    
    - name: Test installer creation
      run: |
        cd build  
        ./build_installer.bat
        
        # Verify installer exists
        if (!(Test-Path "../releases/PortalReceiptsApp_Setup_v1.0.0.exe")) {
          throw "Installer not created"
        }
        
        echo "✅ Installer build successful"
